package com.planting.online.onlineplanting.Dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.planting.online.onlineplanting.Entity.Profile;
import com.planting.online.onlineplanting.Entity.User;

import com.planting.online.onlineplanting.Dao.ProfileDao;
import com.planting.online.onlineplanting.Dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig profileDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ProfileDao profileDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        profileDaoConfig = daoConfigMap.get(ProfileDao.class).clone();
        profileDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        profileDao = new ProfileDao(profileDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Profile.class, profileDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        profileDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ProfileDao getProfileDao() {
        return profileDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
