package com.planting.online.onlineplanting.Dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.planting.online.onlineplanting.Entity.Converter.ImageGroupConverter;
import java.util.List;

import com.planting.online.onlineplanting.Entity.ImageGroup;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IMAGE_GROUP".
*/
public class ImageGroupDao extends AbstractDao<ImageGroup, Long> {

    public static final String TABLENAME = "IMAGE_GROUP";

    /**
     * Properties of entity ImageGroup.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Desc = new Property(1, String.class, "desc", false, "DESC");
        public final static Property Timestamp = new Property(2, String.class, "timestamp", false, "TIMESTAMP");
        public final static Property Imgs = new Property(3, String.class, "imgs", false, "IMGS");
    }

    private final ImageGroupConverter imgsConverter = new ImageGroupConverter();

    public ImageGroupDao(DaoConfig config) {
        super(config);
    }
    
    public ImageGroupDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IMAGE_GROUP\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DESC\" TEXT," + // 1: desc
                "\"TIMESTAMP\" TEXT," + // 2: timestamp
                "\"IMGS\" TEXT);"); // 3: imgs
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IMAGE_GROUP\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ImageGroup entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(2, desc);
        }
 
        String timestamp = entity.getTimestamp();
        if (timestamp != null) {
            stmt.bindString(3, timestamp);
        }
 
        List imgs = entity.getImgs();
        if (imgs != null) {
            stmt.bindString(4, imgsConverter.convertToDatabaseValue(imgs));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ImageGroup entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(2, desc);
        }
 
        String timestamp = entity.getTimestamp();
        if (timestamp != null) {
            stmt.bindString(3, timestamp);
        }
 
        List imgs = entity.getImgs();
        if (imgs != null) {
            stmt.bindString(4, imgsConverter.convertToDatabaseValue(imgs));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ImageGroup readEntity(Cursor cursor, int offset) {
        ImageGroup entity = new ImageGroup( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // desc
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // timestamp
            cursor.isNull(offset + 3) ? null : imgsConverter.convertToEntityProperty(cursor.getString(offset + 3)) // imgs
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ImageGroup entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDesc(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTimestamp(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setImgs(cursor.isNull(offset + 3) ? null : imgsConverter.convertToEntityProperty(cursor.getString(offset + 3)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ImageGroup entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ImageGroup entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ImageGroup entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
